---
Name: prefixrequirements
After: coreresources
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Core\Manifest\ResourceURLGenerator:
    class: Innoweb\PrefixRequirements\Control\PrefixResourceURLGenerator
    properties:
      nonceStyle: mtime

Innoweb\PrefixRequirements\Control\PrefixResourceURLGenerator:
  excluded_resources:
    - 'themes/startup-theme/css/startup.css'
